run:
  timeout: 30m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters:
  enable:
    - deadcode     # Finds unused code
    - errcheck     # Checks for unchecked errors
    - goconst      # Finds repeated strings that could be replaced by a constant
    - gofmt        # Checks Go code formatting
    - goimports    # Checks import statements and formatting of Go code
    - golint       # Reports style mistakes in Go code
    - gosec        # Inspects Go code for security issues
    - gosimple     # Suggests simplifications in Go code
    - govet        # Reports potential errors in Go code
    - ineffassign  # Detects ineffectual assignments in Go code
    - interfacer   # Suggests narrower interfaces that can be used
    - maligned     # Detects structs that could be smaller
    - misspell     # Finds commonly misspelled English words in comments
    - staticcheck  # Provides static analysis of Go code
    - structcheck  # Reports about struct initialization in Go code
    - typecheck    # Checks Go code for type-related mistakes
    - unconvert    # Finds unnecessary type conversions in Go code
    - unparam      # Finds unused function parameters in Go code
    - unused       # Finds unused global variables and constants
    - varcheck     # Finds unused global variables and constants
    - whitespace   # Checks for unexpected whitespace in Go code
