linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - structcheck
    - unused

issues:
  exclude-use-default: false

run:
  timeout: 5m
  tests: true

output:
  format: colored-line-number
  sort-results: true
  print-issued-lines: true
