name: golangci-lint

on:
  push:
    branches:
      - main
      - master
      - devel
      - dev-linter
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    strategy:
      matrix:
        go: ['1.22']
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Lint
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
